# Generated by Django 3.0.5 on 2020-04-30 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_nom', models.CharField(max_length=50, verbose_name='Nombres')),
                ('Emp_ide', models.CharField(max_length=10, verbose_name='Cedula')),
                ('Emp_FeR', models.DateField(default=datetime.datetime.now, verbose_name='FechaR')),
                ('Emp_FeC', models.DateTimeField(auto_now=True)),
                ('Emp_FeU', models.DateTimeField(auto_now_add=True)),
                ('Emp_eda', models.PositiveIntegerField(default=0)),
                ('Emp_sal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Emp_sta', models.BooleanField(default=True)),
                ('Emp_ava', models.ImageField(blank=True, null=True, upload_to='Avatar%Y%m%d')),
                ('Emp_cvi', models.FileField(blank=True, null=True, upload_to='Cvitae%Y%m%d')),
            ],
        ),
    ]
